name: Build Kivy App for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Используем Python 3.10 для совместимости с Kivy

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy==2.3.0 pyinstaller==6.10.0
          pip install kivy-deps.sdl2 kivy-deps.glew kivy-deps.gstreamer

      - name: Build with PyInstaller
        run: |
          pyinstaller --name OR_Code \
                      --windowed \
                      --add-data "assets:assets" \
                      main.py

      - name: Archive the app
        run: |
          zip -r OR_Code.zip dist/OR_Code.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OR_Code
          path: OR_Code.zip
